loki:
  auth_enabled: false

  limits_config:
    retention_period: 240h
    max_entries_limit_per_query: 5000
    max_chunks_per_query: 200000
    reject_old_samples: true
    reject_old_samples_max_age: 24h
    ingestion_rate_mb: 1000
    ingestion_burst_size_mb: 1500
    max_query_series: 100000
    max_label_value_length: 10000
    max_label_names_per_series: 1000
    max_line_size: 2048KB
    max_line_size_truncate: true
    max_streams_per_user: 0
    max_global_streams_per_user: 0
    per_stream_rate_limit: 512MB
    per_stream_rate_limit_burst: 1024MB

  schemaConfig:
    configs:
    - from: "2024-04-01"
      store: tsdb
      object_store: azure
      schema: v13
      index:
        prefix: loki_index_
        period: 24h
  storage_config:
    azure:
      account_name: "<AZURE_STORAGE_ACCOUNT>" # Replace with Azure Storage Account Name
      account_key: "<AZURE_STORAGE_KEY>" # Replace with Azure Storage Account Key
      container_name: "loki-new" # Your actual Azure Blob Storage container name
      use_federated_token: false # Use federated token for authentication
  ingester:
    chunk_encoding: snappy
  pattern_ingester:
    enabled: true
  compactor:
    retention_enabled: true
    delete_request_store: azure
  ruler:
    enable_api: true
    storage:
      type: azure
      azure:
        account_name: "<AZURE_STORAGE_ACCOUNT>" # Replace with Azure Storage Account Name
        account_key: "<AZURE_STORAGE_KEY>" # Replace with Azure Storage Account Key
        container_name: "ruler" # Your actual Azure Blob Storage container name
        use_federated_token: false # Use federated token for authentication
      alertmanager_url: "http://prom:9093" # The URL of the Alertmanager to send alerts
  querier:
    max_concurrent: 4
  storage:
    type: azure
    bucketNames:
      chunks: "loki-new" # Your actual Azure Blob Storage container name
      ruler: "ruler" # Your actual Azure Blob Storage container name
    azure:
      accountName: "<AZURE_STORAGE_ACCOUNT>" # Replace with Azure Storage Account Name
      account_key: "<AZURE_STORAGE_KEY>" # Replace with Azure Storage Account Key
      useFederatedToken: false # Use federated token for authentication

serviceAccount:
  name: loki

deploymentMode: Distributed

ingester:
  replicas: 2
  zoneAwareReplication:
    enabled: false

querier:
  replicas: 2
  maxUnavailable: 2

queryFrontend:
  replicas: 2
  maxUnavailable: 1

queryScheduler:
  replicas: 2

distributor:
  replicas: 2
  maxUnavailable: 2
compactor:
  replicas: 1

indexGateway:
  replicas: 2
  maxUnavailable: 1

ruler:
  replicas: 1
  maxUnavailable: 1

gateway:
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: 'true'
  basicAuth:
    enabled: true
    existingSecret: loki-basic-auth

lokiCanary:
  extraArgs:
  - -pass=$(LOKI_PASS)
  - -user=$(LOKI_USER)
  extraEnv:
  - name: LOKI_PASS
    valueFrom:
      secretKeyRef:
        name: canary-basic-auth
        key: password
  - name: LOKI_USER
    valueFrom:
      secretKeyRef:
        name: canary-basic-auth
        key: username

minio:
  enabled: false

backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

singleBinary:
  replicas: 0