apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-exporter
  namespace: prod-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-exporter
      version: v1
  template:
    metadata:
      labels:
        app: event-exporter
        version: v1
    spec:
      serviceAccountName: event-exporter
      containers:
      - name: event-exporter
        image: ghcr.io/opsgenie/kubernetes-event-exporter:v0.11 # Ensure the image version is appropriate for your use case
        imagePullPolicy: IfNotPresent
        args:
        - -conf=/data/config.yaml
        volumeMounts:
        - mountPath: /data
          name: cfg
      volumes:
      - name: cfg
        configMap:
          name: event-exporter-cfg # Ensure this ConfigMap is available in the same namespace