apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: prod-monitoring
  name: event-exporter
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: event-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view # Grants read-only access; ensure this role has the necessary permissions
subjects:
- kind: ServiceAccount
  namespace: prod-monitoring
  name: event-exporter # Links the service account to the ClusterRoleBinding