apiVersion: v1
kind: Service
metadata:
  name: prod-prometheus-service
  namespace: prod-monitoring
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: 'true'
spec:
  type: LoadBalancer
  selector:
    app: prod-prometheus-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9090