apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-prometheus
  namespace: prod-monitoring
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: azurefile-csi-nfs
  volumeName: pv-prometheus
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: file.csi.azure.com
  name: pv-prometheus
  namespace: prod-monitoring
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile-csi-nfs
  csi:
    driver: file.csi.azure.com
    volumeHandle: "prod-rg-sta-prodmonitoringstaa-prometheus" # make sure this volumeid is unique for every identical share in the cluster
    volumeAttributes:
      shareName: prometheus
    nodeStageSecretRef:
      name: azure-secret
      namespace: prod-monitoring
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
  - nosharesock
  - nobrl # disable sending byte range lock requests to the server and for applications which have challenges with posix locks